/**
 * Chart data schema (spec Section 5.4). One JSON file per track lives in src/charts/,
 * generated at build time by scripts/generateCharts.mjs and committed to the repo.
 * Runtime never computes charts on-device.
 */

export type Difficulty = 'easy' | 'medium' | 'hard' | 'expert';

export const DIFFICULTY_ORDER: Difficulty[] = ['easy', 'medium', 'hard', 'expert'];

/** Note type is a field even though only "tap" ships in v1, so "hold" can be added
 *  later without a schema break (spec Section 5.4 note). */
export type NoteType = 'tap' | 'hold';

export interface ChartNote {
  timeMs: number;
  lane: number;
  type: NoteType;
  /** Duration for hold notes; absent/0 for taps. Reserved for v2. */
  holdMs?: number;
}

export interface HitWindowMs {
  perfect: number;
  great: number;
  good: number;
}

export interface DifficultyChart {
  laneCount: number;
  hitWindowMs: HitWindowMs;
  notes: ChartNote[];
  /** Present on expert only. */
  unlockRequirement?: {
    difficulty: Difficulty;
    minPerfectPercent: number;
  };
  /** True when produced algorithmically and not yet hand-passed by ear (spec 5.3). */
  autoGenerated?: boolean;
}

export interface MoodSample {
  timeMs: number;
  /** Normalized 0..1 energy. */
  energy: number;
}

export interface TrackChart {
  trackId: string;
  title: string;
  audioFile: string;
  durationMs: number;
  bpm: number;
  difficulties: Record<Difficulty, DifficultyChart>;
  moodCurve: {
    description: string;
    samples: MoodSample[];
  };
}
