/**
 * Chart data schema (spec Section 5.4). One JSON file per track lives in src/charts/,
 * generated at build time by scripts/generateCharts.mjs and committed to the repo.
 * Runtime never computes charts on-device.
 */

export type Difficulty = 'easy' | 'medium' | 'hard' | 'expert';

export const DIFFICULTY_ORDER: Difficulty[] = ['easy', 'medium', 'hard', 'expert'];

/** Note types: tap, hold (freeze — press & hold in place), and slide (a hold whose body
 *  travels across lanes; the player drags to follow it — Chunithm-style, judged like a freeze). */
export type NoteType = 'tap' | 'hold' | 'slide';

/** A waypoint on a slide's path: the lane the slide occupies at a given time. */
export interface SlidePoint {
  tMs: number;
  lane: number;
}

export interface ChartNote {
  timeMs: number;
  lane: number;
  type: NoteType;
  /** Duration for hold/slide notes; absent/0 for taps. */
  holdMs?: number;
  /**
   * Slide path (present only on type "slide"): lane over time from head to tail, starting at
   * {timeMs, lane}. The slide's lane is linearly interpolated between consecutive points.
   */
  path?: SlidePoint[];
  /**
   * Beat-subdivision color class (DDR-style note coloring), computed at build time from the
   * real beat grid: 0 = red (on-beat / 4th), 1 = blue (8th / off-beat), 2 = yellow (16th),
   * 3 = green (triplet). Absent is treated as 0.
   */
  c?: number;
}

export interface HitWindowMs {
  perfect: number;
  great: number;
  good: number;
}

export interface DifficultyChart {
  laneCount: number;
  hitWindowMs: HitWindowMs;
  notes: ChartNote[];
  /** Present on expert only. */
  unlockRequirement?: {
    difficulty: Difficulty;
    minPerfectPercent: number;
  };
  /** True when produced algorithmically and not yet hand-passed by ear (spec 5.3). */
  autoGenerated?: boolean;
}

export interface MoodSample {
  timeMs: number;
  /** Normalized 0..1 energy. */
  energy: number;
}

export interface TrackChart {
  trackId: string;
  title: string;
  audioFile: string;
  durationMs: number;
  bpm: number;
  difficulties: Record<Difficulty, DifficultyChart>;
  moodCurve: {
    description: string;
    samples: MoodSample[];
  };
}
