#!/usr/bin/env node
/**
 * Rhythm Riot — chart generator (spec Section 5.2).
 *
 * Consumes REAL librosa analysis (scripts/analysis_real.json, produced by scripts/analyze.py)
 * and turns each track's actual onset list + energy envelope into committed per-track chart
 * JSON for Easy / Medium / Hard, plus a scaffolded 5-lane Expert. Charts are a build-time
 * asset — never computed on-device (spec 5.2 / 9).
 *
 * Note placement is now anchored to detected onsets (not a synthesized grid):
 *   - Easy   : onsets snapped to the beat grid, strongest kept, ~50% of onsets, >=250ms apart
 *   - Medium : strongest ~75% of onsets, 4 lanes
 *   - Hard   : ~100% of onsets incl. sub-beat syncopation, 4 lanes, tight spacing
 *   - Expert : Hard's onset set + energy-driven flourishes on drops, 5 lanes (autoGenerated —
 *              meant to be hand-passed by ear before shipping as "final", spec 5.3)
 *
 * Lane assignment and flourishes are seeded → regeneration is byte-identical (enforced by test).
 * If scripts/analysis_real.json is missing, run `python3 scripts/analyze.py` first.
 *
 * Run:  node scripts/generateCharts.mjs   (also runs automatically on `npm run build`)
 */

import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(__dirname, '..', 'src', 'charts');
const ANALYSIS_PATH = join(__dirname, 'analysis_real.json');

const TRACKS = [
  { id: 'i_dont_care_tonight', title: "I Don't Care Tonight", audioFile: 'i_dont_care_tonight.mp3' },
  { id: 'where_the_inside_opens_wide', title: 'Where the Inside Opens Wide', audioFile: 'where_the_inside_opens_wide.mp4' },
  { id: 'who_moved_the_moon', title: 'Who Moved the Moon', audioFile: 'who_moved_the_moon.mp4' },
  { id: 'dub_steps_trip', title: 'Dub Steps Trip', audioFile: 'dub_steps_trip.mp4' },
  { id: 'everyday_g', title: 'Everyday G', audioFile: 'everyday_g.mp4' },
];

const HIT_WINDOWS = {
  easy: { perfect: 120, great: 200, good: 280 },
  medium: { perfect: 100, great: 170, good: 240 },
  hard: { perfect: 80, great: 140, good: 200 },
  expert: { perfect: 60, great: 110, good: 160 },
};

const DIFF_CONFIG = {
  // holdFraction is a CEILING on how many taps become holds. It ramps up with difficulty so
  // holds read as skill-gated accents (beginners get the fewest); naturally-sparse tracks stay
  // below the ceiling on their own.
  easy: { laneCount: 3, onsetFraction: 0.5, minSpacingMs: 250, snapToBeat: true, holdFraction: 0.10 },
  medium: { laneCount: 4, onsetFraction: 0.75, minSpacingMs: 170, snapToBeat: false, holdFraction: 0.11 },
  hard: { laneCount: 4, onsetFraction: 1.0, minSpacingMs: 105, snapToBeat: false, holdFraction: 0.12 },
  expert: { laneCount: 5, onsetFraction: 1.0, minSpacingMs: 85, snapToBeat: false, holdFraction: 0.13 },
};

// Hold-note tuning (spec 5.4 "hold" type). Holds are now PITCH-BASED: a note becomes a hold only
// where pYIN found a genuinely held note (a stable-pitch segment — see analyze.py), and the hold
// LENGTH equals how long that note is actually held. The tail always ends a hair before the next
// note in the SAME lane, so a hold can span other lanes' notes but never doubles up in its own.
const HOLD_RELEASE_BUFFER_MS = 120; // tail ends this far before the next same-lane note
const HOLD_MIN_MS = 320; // shorter than this isn't worth being a hold
const HOLD_CAP_MS = 3400; // never longer than this
const HOLD_ATTACK_TOL_MS = 150; // a note counts as a held note if it lands within this of the segment's start

/* ------------------------------ RNG ------------------------------ */

function hashSeed(str) {
  let h = 1779033703 ^ str.length;
  for (let i = 0; i < str.length; i++) {
    h = Math.imul(h ^ str.charCodeAt(i), 3432918353);
    h = (h << 13) | (h >>> 19);
  }
  return h >>> 0;
}

function mulberry32(seed) {
  let a = seed >>> 0;
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/* ------------------------ energy sampling ------------------------ */

function sampleEnvelope(env, tMs) {
  if (env.length === 0) return 0.3;
  if (tMs <= env[0].tMs) return env[0].e;
  const last = env[env.length - 1];
  if (tMs >= last.tMs) return last.e;
  for (let i = 1; i < env.length; i++) {
    if (tMs < env[i].tMs) {
      const a = env[i - 1];
      const b = env[i];
      const f = (tMs - a.tMs) / (b.tMs - a.tMs);
      return a.e + (b.e - a.e) * f;
    }
  }
  return last.e;
}

/* --------------------- note selection core ---------------------- */

// Snap onsets to the nearest beat, keeping the strongest onset per beat.
function snapToBeats(onsets, beatsMs) {
  if (beatsMs.length === 0) return onsets.slice();
  const byBeat = new Map();
  let bi = 0;
  for (const o of onsets) {
    // advance beat pointer to nearest beat
    while (bi < beatsMs.length - 1 && Math.abs(beatsMs[bi + 1] - o.tMs) <= Math.abs(beatsMs[bi] - o.tMs)) {
      bi++;
    }
    // (bi only moves forward; onsets are time-sorted so this is fine)
    const beatT = beatsMs[bi];
    const prev = byBeat.get(beatT);
    if (!prev || o.strength > prev.strength) {
      byBeat.set(beatT, { tMs: beatT, strength: o.strength, energy: o.energy });
    }
  }
  return [...byBeat.values()].sort((a, b) => a.tMs - b.tMs);
}

// Greedily accept the strongest notes that respect min spacing; cap at targetCount.
function selectNotes(candidates, targetCount, minSpacingMs) {
  const byStrength = [...candidates].sort((a, b) => b.strength - a.strength);
  const accepted = [];
  const acceptedTimes = [];
  const tooClose = (t) => {
    for (let i = 0; i < acceptedTimes.length; i++) {
      if (Math.abs(acceptedTimes[i] - t) < minSpacingMs) return true;
    }
    return false;
  };
  for (const c of byStrength) {
    if (accepted.length >= targetCount) break;
    if (tooClose(c.tMs)) continue;
    accepted.push(c);
    acceptedTimes.push(c.tMs);
  }
  accepted.sort((a, b) => a.tMs - b.tMs);
  return accepted;
}

// Energy-clustered lane wander that stays playable. Returns notes carrying lane + energy so
// hold marking (which needs same-lane gaps) can run afterward.
function assignLanes(trackId, diff, notes, laneCount) {
  const rng = mulberry32(hashSeed(`${trackId}::${diff}::lanes`));
  let lane = Math.floor(rng() * laneCount);
  let repeat = 0;
  return notes.map((n) => {
    const spread = 1 + Math.floor((n.energy ?? 0.4) * (laneCount - 1));
    let next;
    let guard = 0;
    do {
      const dir = rng() < 0.5 ? -1 : 1;
      const step = 1 + Math.floor(rng() * spread);
      next = Math.max(0, Math.min(laneCount - 1, lane + dir * step));
      guard++;
    } while (next === lane && repeat >= 1 && guard < 6);
    if (next === lane) repeat++;
    else repeat = 0;
    lane = next;
    return { timeMs: n.tMs, lane, energy: n.energy ?? 0.4, type: 'tap' };
  });
}

// Place holds on sustained parts of the song (see tuning above). Mutates notes (type + holdMs).
function markHolds(trackId, diff, notes, analysis) {
  const cfg = DIFF_CONFIG[diff];
  const rng = mulberry32(hashSeed(`${trackId}::${diff}::holds`));

  // For each note, find the next note in the same lane.
  const nextSameLane = new Array(notes.length).fill(-1);
  const lastByLane = {};
  for (let i = notes.length - 1; i >= 0; i--) {
    const lane = notes[i].lane;
    if (lastByLane[lane] !== undefined) nextSameLane[i] = lastByLane[lane];
    lastByLane[lane] = i;
  }

  // PITCH-BASED: holds land on actual held notes (stable-pitch segments from pYIN, see
  // analyze.py), with length = how long that note is held — clamped by same-lane room + cap.
  const segs = (analysis.sustainSegments || []).slice().sort((a, b) => a.startMs - b.startMs);

  // Find the held-note segment whose ATTACK lines up with a note (the note is that held note).
  const segForNote = (tMs) => {
    let best = null;
    let bestErr = HOLD_ATTACK_TOL_MS;
    for (const s of segs) {
      if (s.startMs > tMs + HOLD_ATTACK_TOL_MS) break;
      const err = Math.abs(s.startMs - tMs);
      if (err <= bestErr) {
        bestErr = err;
        best = s;
      }
    }
    return best;
  };

  const candidates = [];
  for (let i = 0; i < notes.length; i++) {
    const j = nextSameLane[i];
    const nextT = j < 0 ? analysis.durationMs : notes[j].timeMs;
    const room = Math.min(nextT - notes[i].timeMs - HOLD_RELEASE_BUFFER_MS, HOLD_CAP_MS);
    if (room < HOLD_MIN_MS) continue;
    const seg = segForNote(notes[i].timeMs);
    if (!seg) continue; // no held note here → stays a tap
    const heldMs = seg.endMs - notes[i].timeMs; // to the end of the held note
    const holdMs = Math.min(heldMs, room);
    if (holdMs < HOLD_MIN_MS) continue;
    candidates.push({ i, holdMs });
  }
  // Chronological placement so every qualifying held note can become a hold; jitter only breaks
  // ties for the same-lane cooldown, keeping it deterministic.
  candidates.sort((a, b) => notes[a.i].timeMs - notes[b.i].timeMs + (rng() - 0.5) * 2);

  const targetHolds = Math.round(notes.length * cfg.holdFraction);
  const lastHoldTimeByLane = {};
  let placed = 0;
  for (const c of candidates) {
    if (placed >= targetHolds) break;
    const n = notes[c.i];
    // Don't stack two holds too close in the same lane.
    const lastT = lastHoldTimeByLane[n.lane];
    if (lastT !== undefined && n.timeMs - lastT < 900) continue;
    n.type = 'hold';
    n.holdMs = Math.round(c.holdMs);
    lastHoldTimeByLane[n.lane] = n.timeMs;
    placed++;
  }
}

// DDR-style beat-subdivision color of a note, from the REAL beat grid. Returns:
//   0 = red    (on-beat / quarter)     2 = yellow (16th)
//   1 = blue   (8th / off-beat)        3 = green  (triplet / 12th)
// Notes that don't snap cleanly default to blue (an off-beat), which keeps the field colorful
// without lying about strong downbeats.
function classifyColor(tMs, beatsMs) {
  if (!beatsMs || beatsMs.length < 2) return 0;
  let i = 0;
  while (i < beatsMs.length - 1 && beatsMs[i + 1] <= tMs) i++;
  let b0 = beatsMs[i];
  let b1 = beatsMs[i + 1] ?? b0 + (b0 - (beatsMs[i - 1] ?? b0 - 500));
  if (tMs < beatsMs[0]) {
    b1 = beatsMs[0];
    b0 = beatsMs[0] - (beatsMs[1] - beatsMs[0]);
  }
  const span = b1 - b0 || 500;
  let frac = (tMs - b0) / span;
  frac -= Math.floor(frac); // 0..1 within the beat
  const near = (x, tol) => Math.min(Math.abs(frac - x), Math.abs(frac - x + 1), Math.abs(frac - x - 1)) <= tol;
  const tol = 0.1;
  if (near(0, tol)) return 0; // downbeat → red
  if (near(0.5, tol)) return 1; // & → blue
  if (near(1 / 3, tol) || near(2 / 3, tol)) return 3; // triplet → green
  if (near(0.25, tol) || near(0.75, tol)) return 2; // 16th → yellow
  return 1;
}

// Keep the grid CLEAR while a sustain is held: drop every other note (any lane) whose time falls
// inside a hold's span. Holding one arrow while tapping others is the classic DDR difficulty spike
// and also causes arrows to visually collide with the freeze body — this removes both. Hold heads
// (and other holds) are always kept; only taps landing during a sustain are pruned.
function clearHoldOverlaps(notes) {
  const holds = notes.filter((n) => n.type === 'hold');
  if (!holds.length) return notes;
  const HEAD_GUARD = 30; // don't nuke a note sitting essentially on the hold's own onset frame
  const TAIL_GUARD = 90; // let a note land right as the sustain releases
  return notes.filter((n) => {
    if (n.type === 'hold') return true;
    for (const h of holds) {
      const start = h.timeMs;
      const end = h.timeMs + (h.holdMs || 0);
      if (n.timeMs >= start - HEAD_GUARD && n.timeMs <= end - TAIL_GUARD) return false;
    }
    return true;
  });
}

// Strip internal fields and emit the committed note shape (with DDR color class `c`).
function finalizeNotes(notes, beatsMs) {
  return notes.map((n) => {
    const c = classifyColor(n.timeMs, beatsMs);
    return n.type === 'hold'
      ? { timeMs: n.timeMs, lane: n.lane, type: 'hold', holdMs: n.holdMs, c }
      : { timeMs: n.timeMs, lane: n.lane, type: 'tap', c };
  });
}

function buildDifficulty(trackId, diff, analysis) {
  const cfg = DIFF_CONFIG[diff];
  let candidates = analysis.onsets;
  if (cfg.snapToBeat) candidates = snapToBeats(analysis.onsets, analysis.beatsMs);
  const target = Math.round(analysis.numOnsets * cfg.onsetFraction);
  const picked = selectNotes(candidates, target, cfg.minSpacingMs);
  const notes = assignLanes(trackId, diff, picked, cfg.laneCount);
  markHolds(trackId, diff, notes, analysis);
  return finalizeNotes(clearHoldOverlaps(notes), analysis.beatsMs);
}

// Expert: Hard's real-onset set (5-lane) + energy-driven flourishes on the hottest hits.
function buildExpert(trackId, analysis) {
  const cfg = DIFF_CONFIG.expert;
  const base = selectNotes(analysis.onsets, analysis.numOnsets, cfg.minSpacingMs);

  // Adaptive threshold: top ~20% by energy always yields flourish candidates.
  const energies = base.map((n) => n.energy).sort((a, b) => a - b);
  const threshold = energies.length ? energies[Math.floor(energies.length * 0.8)] : 0.8;

  const rng = mulberry32(hashSeed(`${trackId}::expert::flourish`));
  const beatMs = 60000 / analysis.bpm;
  const times = base.map((n) => n.tMs);
  const isFree = (t) => times.every((x) => Math.abs(x - t) >= cfg.minSpacingMs);

  const extras = [];
  for (const n of base) {
    if (n.energy >= threshold && rng() < 0.5) {
      const t2 = Math.round(n.tMs + beatMs / 4);
      if (t2 < analysis.durationMs && isFree(t2)) {
        extras.push({ tMs: t2, strength: n.strength, energy: n.energy });
        times.push(t2);
      }
    }
  }

  const all = [...base, ...extras].sort((a, b) => a.tMs - b.tMs);
  const notes = assignLanes(trackId, 'expert', all, cfg.laneCount);
  markHolds(trackId, 'expert', notes, analysis);
  return finalizeNotes(clearHoldOverlaps(notes), analysis.beatsMs);
}

function buildMoodCurve(env, durationMs) {
  const sampleEveryMs = 2000;
  const samples = [];
  for (let t = 0; t <= durationMs; t += sampleEveryMs) {
    samples.push({ timeMs: t, energy: Number(sampleEnvelope(env, t).toFixed(3)) });
  }
  return samples;
}

/* ------------------------------ main ----------------------------- */

function generate() {
  if (!existsSync(ANALYSIS_PATH)) {
    console.error(`Missing ${ANALYSIS_PATH}. Run: python3 scripts/analyze.py`);
    process.exit(1);
  }
  const analysisAll = JSON.parse(readFileSync(ANALYSIS_PATH, 'utf8'));
  mkdirSync(OUT_DIR, { recursive: true });
  const summary = [];

  for (const track of TRACKS) {
    const a = analysisAll[track.id];
    if (!a) {
      console.error(`No analysis for ${track.id}`);
      process.exit(1);
    }

    const difficulties = {
      easy: { laneCount: 3, hitWindowMs: HIT_WINDOWS.easy, notes: buildDifficulty(track.id, 'easy', a), autoGenerated: true },
      medium: { laneCount: 4, hitWindowMs: HIT_WINDOWS.medium, notes: buildDifficulty(track.id, 'medium', a), autoGenerated: true },
      hard: { laneCount: 4, hitWindowMs: HIT_WINDOWS.hard, notes: buildDifficulty(track.id, 'hard', a), autoGenerated: true },
      expert: {
        laneCount: 5,
        hitWindowMs: HIT_WINDOWS.expert,
        unlockRequirement: { difficulty: 'hard', minPerfectPercent: 90 },
        notes: buildExpert(track.id, a),
        autoGenerated: true,
      },
    };

    const chart = {
      trackId: track.id,
      title: track.title,
      audioFile: track.audioFile,
      durationMs: a.durationMs,
      bpm: a.bpm,
      difficulties,
      moodCurve: {
        description:
          'Normalized 0-1 RMS energy at 2s sample points from real librosa analysis (scripts/analyze.py). Target arc for Vibe Score comparison (spec 4.4).',
        samples: buildMoodCurve(a.energyEnvelope, a.durationMs),
      },
    };

    writeFileSync(join(OUT_DIR, `${track.id}.json`), JSON.stringify(chart) + '\n');
    summary.push({
      id: track.id,
      easy: difficulties.easy.notes.length,
      medium: difficulties.medium.notes.length,
      hard: difficulties.hard.notes.length,
      expert: difficulties.expert.notes.length,
    });
  }

  writeFileSync(join(OUT_DIR, 'manifest.json'), JSON.stringify(TRACKS.map((t) => t.id)) + '\n');

  console.log('Generated charts from REAL onset analysis:');
  for (const s of summary) {
    console.log(`  ${s.id.padEnd(30)} easy=${s.easy} medium=${s.medium} hard=${s.hard} expert=${s.expert}`);
  }
  console.log(`Wrote ${summary.length} charts + manifest.json to src/charts/`);
}

generate();
