#!/usr/bin/env node
/**
 * Rhythm Riot — build-time chart generator (spec Section 5.2).
 *
 * Reads the librosa analysis for each launch track and synthesizes deterministic,
 * musically-plausible charts for Easy / Medium / Hard, plus a scaffolded 5-lane Expert.
 * Output: src/charts/<trackId>.json  (committed; NOT computed on-device).
 *
 * The source analysis captured tempo, duration, onset density and energy statistics but
 * not the full onset list, so charts are built on a tempo-derived beat grid whose note
 * placement is weighted by a synthesized energy curve. Everything is seeded, so re-running
 * this script reproduces byte-identical charts.
 *
 * Expert charts are marked { autoGenerated: true } — per spec 5.3 they are meant to be
 * hand-passed by ear before shipping as "final" Expert content. They are unlocked-gated,
 * so they are safe to ship as scaffolding in v1.
 *
 * Run:  node scripts/generateCharts.mjs   (also runs automatically on `npm run build`)
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(__dirname, '..', 'src', 'charts');

/* ------------------------------------------------------------------ */
/* Analysis (mirror of src/data/trackAnalysis.ts + tracks.ts)          */
/* ------------------------------------------------------------------ */

const TRACKS = [
  { id: 'i_dont_care_tonight', title: "I Don't Care Tonight", audioFile: 'i_dont_care_tonight.mp3' },
  { id: 'where_the_inside_opens_wide', title: 'Where the Inside Opens Wide', audioFile: 'where_the_inside_opens_wide.mp3' },
  { id: 'who_moved_the_moon', title: 'Who Moved the Moon', audioFile: 'who_moved_the_moon.mp3' },
  { id: 'dub_steps_trip', title: 'Dub Steps Trip', audioFile: 'dub_steps_trip.mp3' },
  { id: 'everyday_g', title: 'Everyday G', audioFile: 'everyday_g.mp3' },
];

const ANALYSIS = {
  i_dont_care_tonight: { duration_sec: 173.08, tempo_bpm: 103.4, num_onsets: 599, avg_energy: 0.1282, peak_energy: 0.3846, energy_std: 0.0686, high_energy_window_count: 121, first_beat: 0.163 },
  where_the_inside_opens_wide: { duration_sec: 231.05, tempo_bpm: 129.2, num_onsets: 826, avg_energy: 0.17, peak_energy: 0.488, energy_std: 0.0893, high_energy_window_count: 293, first_beat: 9.125 },
  who_moved_the_moon: { duration_sec: 243.05, tempo_bpm: 95.7, num_onsets: 865, avg_energy: 0.1903, peak_energy: 0.3956, energy_std: 0.08, high_energy_window_count: 829, first_beat: 5.224 },
  dub_steps_trip: { duration_sec: 265.81, tempo_bpm: 136.0, num_onsets: 949, avg_energy: 0.187, peak_energy: 0.4477, energy_std: 0.0812, high_energy_window_count: 359, first_beat: 4.899 },
  everyday_g: { duration_sec: 214.69, tempo_bpm: 152.0, num_onsets: 952, avg_energy: 0.1484, peak_energy: 0.4115, energy_std: 0.0723, high_energy_window_count: 508, first_beat: 0.163 },
};

const HIT_WINDOWS = {
  easy: { perfect: 120, great: 200, good: 280 },
  medium: { perfect: 100, great: 170, good: 240 },
  hard: { perfect: 80, great: 140, good: 200 },
  expert: { perfect: 60, great: 110, good: 160 },
};

const DIFF_CONFIG = {
  easy: { laneCount: 3, onsetFraction: 0.5, minSpacingMs: 250, maxSubdiv: 1 },
  medium: { laneCount: 4, onsetFraction: 0.75, minSpacingMs: 170, maxSubdiv: 2 },
  hard: { laneCount: 4, onsetFraction: 1.0, minSpacingMs: 110, maxSubdiv: 4 },
  expert: { laneCount: 5, onsetFraction: 1.18, minSpacingMs: 90, maxSubdiv: 4 },
};

/* ------------------------------------------------------------------ */
/* Deterministic RNG                                                   */
/* ------------------------------------------------------------------ */

function hashSeed(str) {
  let h = 1779033703 ^ str.length;
  for (let i = 0; i < str.length; i++) {
    h = Math.imul(h ^ str.charCodeAt(i), 3432918353);
    h = (h << 13) | (h >>> 19);
  }
  return h >>> 0;
}

function mulberry32(seed) {
  let a = seed >>> 0;
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/* ------------------------------------------------------------------ */
/* Energy curve synthesis                                              */
/* ------------------------------------------------------------------ */

function cosineInterp(a, b, t) {
  const f = (1 - Math.cos(t * Math.PI)) / 2;
  return a * (1 - f) + b * f;
}

/**
 * Build a normalized 0..1 energy curve sampled every `stepSec` across the song.
 * Baseline is anchored to avg/peak ratio; variation amplitude scales with energy_std;
 * high_energy_window_count nudges how much time is spent "hot". Seeded → deterministic.
 */
function buildEnergyCurve(trackId, a, stepSec) {
  const rng = mulberry32(hashSeed(trackId + '::energy'));
  const totalSamples = Math.ceil(a.duration_sec / stepSec) + 1;

  const baseline = Math.min(0.75, Math.max(0.25, a.avg_energy / a.peak_energy));
  // Relative "hotness" nudge from the high-energy window count (saturating, cross-track scaled).
  const hotNudge = Math.min(0.18, a.high_energy_window_count / 3000);
  const variation = Math.min(0.55, 0.35 + a.energy_std * 2.2);

  // Control points every ~6 samples create phrase-level builds/drops.
  const cpEvery = 6;
  const cpCount = Math.ceil(totalSamples / cpEvery) + 2;
  const cps = [];
  for (let i = 0; i < cpCount; i++) {
    // Bias toward builds in the back half (choruses/drops usually land later).
    const progress = i / cpCount;
    const lift = 0.12 * Math.sin(progress * Math.PI); // arc: rises mid/late song
    let v = baseline + hotNudge + lift + (rng() - 0.5) * 2 * variation;
    cps.push(Math.max(0.04, Math.min(1, v)));
  }

  const curve = new Array(totalSamples);
  for (let i = 0; i < totalSamples; i++) {
    const cpPos = i / cpEvery;
    const i0 = Math.floor(cpPos);
    const frac = cpPos - i0;
    curve[i] = cosineInterp(cps[i0], cps[i0 + 1] ?? cps[i0], frac);
  }

  // Normalize so the loudest region reaches ~1 (keeps palettes hitting full mood on peaks).
  const max = Math.max(...curve);
  const scale = max > 0 ? 1 / max : 1;
  for (let i = 0; i < totalSamples; i++) curve[i] = Math.min(1, curve[i] * scale);
  return curve;
}

function sampleCurve(curve, stepSec, timeSec) {
  const x = timeSec / stepSec;
  const i0 = Math.floor(x);
  const frac = x - i0;
  const a = curve[Math.max(0, Math.min(curve.length - 1, i0))];
  const b = curve[Math.max(0, Math.min(curve.length - 1, i0 + 1))];
  return a + (b - a) * frac;
}

/* ------------------------------------------------------------------ */
/* Slot generation + note selection                                    */
/* ------------------------------------------------------------------ */

// Subdivision strengths: index by how the slot sits in the bar/beat.
function buildSlots(a, maxSubdiv) {
  const beatSec = 60 / a.tempo_bpm;
  const startPhase = ((a.first_beat % beatSec) + beatSec) % beatSec;
  const slots = [];
  let beatIndex = 0;
  for (let t = startPhase; t <= a.duration_sec - 0.05; t += beatSec, beatIndex++) {
    // Strong-beat position within a 4/4 bar.
    const inBar = beatIndex % 4;
    const beatStrength = inBar === 0 ? 1.0 : inBar === 2 ? 0.88 : 0.8;
    slots.push({ timeSec: t, strength: beatStrength, sub: 1 });

    if (maxSubdiv >= 2) {
      slots.push({ timeSec: t + beatSec / 2, strength: 0.62, sub: 2 });
    }
    if (maxSubdiv >= 4) {
      slots.push({ timeSec: t + beatSec / 4, strength: 0.42, sub: 4 });
      slots.push({ timeSec: t + (3 * beatSec) / 4, strength: 0.46, sub: 4 }); // syncopated "e/a"
    }
  }
  return slots.filter((s) => s.timeSec >= 0 && s.timeSec <= a.duration_sec);
}

function selectNotes(trackId, diff, a, curve, stepSec) {
  const cfg = DIFF_CONFIG[diff];
  const rng = mulberry32(hashSeed(`${trackId}::${diff}::notes`));
  const slots = buildSlots(a, cfg.maxSubdiv);

  const target = Math.round(a.num_onsets * cfg.onsetFraction);

  // Score every slot by structural strength × local energy × slight jitter.
  const scored = slots.map((s) => {
    const e = sampleCurve(curve, stepSec, s.timeSec);
    const energyWeight = 0.35 + 0.65 * e;
    const jitter = 0.85 + rng() * 0.3;
    return { ...s, energy: e, score: s.strength * energyWeight * jitter };
  });
  scored.sort((x, y) => y.score - x.score);

  // Greedily accept high-score slots while respecting min spacing.
  const chosen = [];
  const acceptedTimes = [];
  const minSpacingSec = cfg.minSpacingMs / 1000;

  const tooClose = (t) => {
    // Binary-ish scan; lists are a few thousand entries max, linear is fine at build time.
    for (let i = 0; i < acceptedTimes.length; i++) {
      if (Math.abs(acceptedTimes[i] - t) < minSpacingSec) return true;
    }
    return false;
  };

  for (const s of scored) {
    if (chosen.length >= target) break;
    if (tooClose(s.timeSec)) continue;
    chosen.push(s);
    acceptedTimes.push(s.timeSec);
  }

  chosen.sort((x, y) => x.timeSec - y.timeSec);

  // Lane assignment: energy-clustered wander that stays playable.
  const laneRng = mulberry32(hashSeed(`${trackId}::${diff}::lanes`));
  const laneCount = cfg.laneCount;
  let lane = Math.floor(laneRng() * laneCount);
  let repeat = 0;
  const notes = chosen.map((s) => {
    // Higher energy → bigger allowed jump (busier, more spread hands).
    const spread = 1 + Math.floor(s.energy * (laneCount - 1));
    let next;
    let guard = 0;
    do {
      const dir = laneRng() < 0.5 ? -1 : 1;
      const step = 1 + Math.floor(laneRng() * spread);
      next = Math.max(0, Math.min(laneCount - 1, lane + dir * step));
      guard++;
    } while (next === lane && repeat >= 1 && guard < 6);

    if (next === lane) repeat++;
    else repeat = 0;
    lane = next;

    return { timeMs: Math.round(s.timeSec * 1000), lane, type: 'tap' };
  });

  return notes;
}

/* ------------------------------------------------------------------ */
/* Expert flourish pass                                                */
/* ------------------------------------------------------------------ */

function buildExpert(trackId, a, curve, stepSec) {
  // Start from the base expert selection, then add flourish notes in the hottest regions.
  const base = selectNotes(trackId, 'expert', a, curve, stepSec);
  const rng = mulberry32(hashSeed(`${trackId}::expert::flourish`));
  const laneCount = DIFF_CONFIG.expert.laneCount;
  const beatSec = 60 / a.tempo_bpm;
  const minSpacingSec = DIFF_CONFIG.expert.minSpacingMs / 1000;

  const times = base.map((n) => n.timeMs / 1000);
  const isFree = (t) => times.every((x) => Math.abs(x - t) >= minSpacingSec);

  const extras = [];
  for (const n of base) {
    const tSec = n.timeMs / 1000;
    const e = sampleCurve(curve, stepSec, tSec);
    // Only in the top energy band, and sparingly — deliberate difficulty spikes on drops.
    if (e > 0.82 && rng() < 0.4) {
      const t2 = tSec + beatSec / 4;
      if (t2 < a.duration_sec && isFree(t2)) {
        const lane = Math.max(0, Math.min(laneCount - 1, n.lane + (rng() < 0.5 ? -2 : 2)));
        extras.push({ timeMs: Math.round(t2 * 1000), lane, type: 'tap' });
        times.push(t2);
      }
    }
  }

  const all = [...base, ...extras].sort((x, y) => x.timeMs - y.timeMs);
  return all;
}

/* ------------------------------------------------------------------ */
/* Mood curve export                                                   */
/* ------------------------------------------------------------------ */

function buildMoodCurve(curve, stepSec) {
  const sampleEveryMs = 2000;
  const samples = [];
  const durationMs = (curve.length - 1) * stepSec * 1000;
  for (let t = 0; t <= durationMs; t += sampleEveryMs) {
    samples.push({ timeMs: t, energy: Number(sampleCurve(curve, stepSec, t / 1000).toFixed(3)) });
  }
  return samples;
}

/* ------------------------------------------------------------------ */
/* Main                                                                */
/* ------------------------------------------------------------------ */

function generate() {
  mkdirSync(OUT_DIR, { recursive: true });
  const stepSec = 0.5;
  const summary = [];

  for (const track of TRACKS) {
    const a = ANALYSIS[track.id];
    const curve = buildEnergyCurve(track.id, a, stepSec);

    const difficulties = {};
    for (const diff of ['easy', 'medium', 'hard']) {
      difficulties[diff] = {
        laneCount: DIFF_CONFIG[diff].laneCount,
        hitWindowMs: HIT_WINDOWS[diff],
        notes: selectNotes(track.id, diff, a, curve, stepSec),
        autoGenerated: true,
      };
    }
    difficulties.expert = {
      laneCount: DIFF_CONFIG.expert.laneCount,
      hitWindowMs: HIT_WINDOWS.expert,
      unlockRequirement: { difficulty: 'hard', minPerfectPercent: 90 },
      notes: buildExpert(track.id, a, curve, stepSec),
      autoGenerated: true,
    };

    const chart = {
      trackId: track.id,
      title: track.title,
      audioFile: track.audioFile,
      durationMs: Math.round(a.duration_sec * 1000),
      bpm: a.tempo_bpm,
      difficulties,
      moodCurve: {
        description:
          'Normalized 0-1 energy at 2s sample points, synthesized from librosa avg/peak/std + high-energy window count. Target arc for Vibe Score comparison (spec 4.4).',
        samples: buildMoodCurve(curve, stepSec),
      },
    };

    const outPath = join(OUT_DIR, `${track.id}.json`);
    writeFileSync(outPath, JSON.stringify(chart) + '\n');
    summary.push({
      id: track.id,
      easy: difficulties.easy.notes.length,
      medium: difficulties.medium.notes.length,
      hard: difficulties.hard.notes.length,
      expert: difficulties.expert.notes.length,
    });
  }

  // Manifest so the loader can enumerate available charts without hardcoding.
  const manifest = TRACKS.map((t) => t.id);
  writeFileSync(join(OUT_DIR, 'manifest.json'), JSON.stringify(manifest) + '\n');

  console.log('Generated charts:');
  for (const s of summary) {
    console.log(
      `  ${s.id.padEnd(30)} easy=${s.easy} medium=${s.medium} hard=${s.hard} expert=${s.expert}`,
    );
  }
  console.log(`Wrote ${summary.length} charts + manifest.json to src/charts/`);
}

generate();
